---

- name: WSGI server | Make sure directory for Gunicorn socket file exists
  file: state=directory path={{ wsgi_sock_path|dirname }}
  become: true

- name: WSGI server | Install Gunicorn
  apt: name=gunicorn state=present
  become: true

- name: WSGI server | Make sure directory for Gunicorn config exists
  file:
    path=/etc/gunicorn.d
    state=directory
  become: true

- name: WSGI server | Push Gunicorn configuration
  template:
    src=templates/gunicorn_app.py.j2
    dest=/etc/gunicorn.d/{{ wsgi_conf_name }}.conf
  become: true
  notify:
    - restart gunicorn

- name: WSGI server | Enable Gunicorn service
  service:
    name: gunicorn
    state: restarted
    enabled: yes
    use: service
  become: true
